project_id = "partspeddle"

[functions.send-message-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-message-notification/deno.json"
entrypoint = "./functions/send-message-notification/index.ts"

[functions.sync-algolia-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/sync-algolia-webhook/deno.json"
entrypoint = "./functions/sync-algolia-webhook/index.ts"

[functions.analyze-part-image]
enabled = true
verify_jwt = false
import_map = "./functions/analyze-part-image/deno.json"
entrypoint = "./functions/analyze-part-image/index.ts"
