import { RouteDefinition } from '../types';

export const marketplaceRoutes = {
  home: {
    id: 'home',
    name: 'Home',
    path: '/',
    title: 'PartsPeddle',
    description: 'Professional marketplace for quality used OEM auto and farm parts.',
    section: 'marketplace',
    visibility: 'public',
    layout: 'public',
    navPosition: ['main'],
    sitemap: true,
    searchable: true,
  },
  search: {
    id: 'search',
    name: 'Search Parts',
    path: '/search',
    title: 'Search Parts',
    description: 'Search millions of used OEM auto and farm parts.',
    section: 'marketplace',
    visibility: 'public',
    layout: 'public',
    navPosition: ['main'],
    sitemap: true,
    searchable: true,
  },
  partDetail: {
    id: 'part-detail',
    name: 'Part Details',
    path: '/listing/:partId',
    title: 'Part Details',
    description: 'View part details, fitment, and seller information.',
    section: 'marketplace',
    visibility: 'public',
    layout: 'public',
    parent: 'search',
    sitemap: false,
    searchable: false,
  },
  partFitment: {
    id: 'part-fitment',
    name: 'Part Fitment',
    path: '/listing/:partId/fitment',
    title: 'Part Fitment',
    description: 'See which vehicles this part fits.',
    section: 'marketplace',
    visibility: 'public',
    layout: 'public',
    parent: 'part-detail',
    sitemap: false,
    searchable: false,
  },
  partCompatible: {
    id: 'part-compatible',
    name: 'Compatible Parts',
    path: '/listing/:partId/compatible-parts',
    title: 'Compatible Parts',
    description: 'Browse parts compatible with this vehicle.',
    section: 'marketplace',
    visibility: 'public',
    layout: 'public',
    parent: 'part-detail',
    sitemap: false,
    searchable: false,
  },
  sellerProfile: {
    id: 'seller-profile',
    name: 'Seller Profile',
    path: '/seller/:sellerId',
    title: 'Seller Profile',
    description: 'View seller inventory, ratings, and profile.',
    section: 'marketplace',
    visibility: 'public',
    layout: 'public',
    sitemap: false,
    searchable: false,
  },
  watchlist: {
    id: 'watchlist',
    name: 'Watchlist',
    path: '/watchlist',
    title: 'Watchlist',
    description: 'Parts you are watching.',
    section: 'buyer',
    visibility: 'authenticated',
    layout: 'public',
    navPosition: ['main'],
    sitemap: false,
  },
  recentlyViewed: {
    id: 'recently-viewed',
    name: 'Recently Viewed',
    path: '/recently-viewed',
    title: 'Recently Viewed',
    description: 'Parts you have viewed recently.',
    section: 'buyer',
    visibility: 'authenticated',
    layout: 'public',
    navPosition: ['main'],
    sitemap: false,
  },
} satisfies Record<string, RouteDefinition>;
