import { supabase } from '../lib/supabase';
import { MOCK_SELLERS, MOCK_PARTS } from './db';

/**
 * Seeding utility to push mock data to Supabase, 
 * updated to match the new schema.
 */
export const seedDatabase = async () => {
  console.log('🚀 Starting Database Seeding...');

  try {
    // 1. Seed Seller Profiles
    console.log('📦 Seeding Seller Profiles...');
    // Note: Mock sellers need a corresponding user. 
    // This assumes users exist or are created first.
    const sellerProfilesToInsert = MOCK_SELLERS.map(s => ({
      // id: s.id, // Assuming id is generated by DB or needs to be a UUID if mapping to users.id
      business_name: s.name,
      // mapping other fields...
    }));

    // This is complex because of relationships with auth.users.
    // Proceeding to seed parts for now, as that's simpler.

    // 2. Seed Parts
    console.log('📦 Seeding Parts...');
    const partsToInsert = MOCK_PARTS.map(p => ({
      title: p.title,
      description: p.description,
      price_mxn: Math.round(p.price * 20), // Mock conversion
      status: 'available',
      compatibility: p.compatibility,
      brand: p.title.split(' ')[0], // Simple mock brand extraction
      model: p.subtitle,
      year: parseInt(p.subtitle.match(/\d{4}/)?.[0] || '0')
    }));

    const { error: partError } = await supabase.from('parts').upsert(partsToInsert);
    if (partError) throw partError;

    console.log('✅ Seeding Complete!');
    return { success: true };
  } catch (error) {
    console.error('❌ Seeding Failed:', error);
    return { success: false, error };
  }
};
