import { RouteDefinition } from '../types';

export const editorialRoutes = {
  about: {
    id: 'about',
    name: 'About',
    path: '/about',
    title: 'About PartsPeddle',
    description:
      'Learn about PartsPeddle, the professional marketplace for quality used OEM auto and farm parts.',
    section: 'company',
    visibility: 'public',
    layout: 'editorial',
    navPosition: ['footer'],
  },
  contact: {
    id: 'contact',
    name: 'Contact',
    path: '/contact',
    title: 'Contact Us',
    description: 'Get in touch with PartsPeddle support, sales, and seller services.',
    section: 'support',
    visibility: 'public',
    layout: 'editorial',
    navPosition: ['footer'],
  },
  terms: {
    id: 'terms',
    name: 'Terms of Service',
    path: '/terms',
    title: 'Terms of Service',
    description: 'Read the PartsPeddle Terms of Service.',
    section: 'legal',
    visibility: 'public',
    layout: 'editorial',
    navPosition: ['footer'],
  },
  privacy: {
    id: 'privacy',
    name: 'Privacy Policy',
    path: '/privacy',
    title: 'Privacy Policy',
    description: 'Read the PartsPeddle Privacy Policy.',
    section: 'legal',
    visibility: 'public',
    layout: 'editorial',
    navPosition: ['footer'],
  },
  trustVerification: {
    id: 'trust-verification',
    name: 'Trust & Verification',
    path: '/trust-verification',
    title: 'Trust & Verification',
    description: 'Learn how PartsPeddle verifies sellers and protects buyers.',
    section: 'company',
    visibility: 'public',
    layout: 'editorial',
    navPosition: ['footer'],
  },
  salvageNetwork: {
    id: 'salvage-network',
    name: 'Salvage Network',
    path: '/salvage-network',
    title: 'Salvage Network',
    description:
      'Join the PartsPeddle Salvage Network of verified dismantlers and independent sellers.',
    section: 'company',
    visibility: 'public',
    layout: 'editorial',
    navPosition: ['footer'],
  },
  helpCenter: {
    id: 'help-center',
    name: 'Help Center',
    path: '/help',
    title: 'Help Center',
    description: 'Find answers and get support.',
    section: 'support',
    visibility: 'public',
    layout: 'editorial',
    featureFlag: 'helpCenter',
    navPosition: ['footer'],
  },
} satisfies Record<string, RouteDefinition>;
