import { RouteDefinition } from '../types';

export const workspaceRoutes = {
  sellerDashboard: {
    id: 'seller-dashboard',
    name: 'Dashboard',
    path: '/seller',
    title: 'Seller Dashboard',
    description: 'Overview of your seller workspace.',
    section: 'seller',
    visibility: 'seller',
    layout: 'workspace',
    navPosition: ['sidebar'],
    sitemap: false,
  },
  sellerInventory: {
    id: 'seller-inventory',
    name: 'Inventory',
    path: '/seller/inventory',
    title: 'Inventory',
    description: 'Manage your parts inventory.',
    section: 'seller',
    visibility: 'seller',
    layout: 'workspace',
    parent: 'seller-dashboard',
    navPosition: ['sidebar'],
    sitemap: false,
  },
  sellerListings: {
    id: 'seller-listings',
    name: 'Listings',
    path: '/seller/listings',
    title: 'Listings',
    description: 'Manage your active listings.',
    section: 'seller',
    visibility: 'seller',
    layout: 'workspace',
    parent: 'seller-dashboard',
    navPosition: ['sidebar'],
    sitemap: false,
  },
  sellerCreate: {
    id: 'seller-create',
    name: 'Create Listing',
    path: '/seller/create',
    title: 'Create Listing',
    description: 'Create a new part listing.',
    section: 'seller',
    visibility: 'seller',
    layout: 'workspace',
    parent: 'seller-dashboard',
    navPosition: ['sidebar'],
    sitemap: false,
  },
  sellerOrders: {
    id: 'seller-orders',
    name: 'Orders',
    path: '/seller/orders',
    title: 'Orders',
    description: 'View and manage orders.',
    section: 'seller',
    visibility: 'seller',
    layout: 'workspace',
    parent: 'seller-dashboard',
    navPosition: ['sidebar'],
    sitemap: false,
  },
  sellerMessages: {
    id: 'seller-messages',
    name: 'Messages',
    path: '/seller/messages',
    title: 'Messages',
    description: 'Buyer messages and inquiries.',
    section: 'seller',
    visibility: 'seller',
    layout: 'workspace',
    parent: 'seller-dashboard',
    navPosition: ['sidebar'],
    sitemap: false,
  },
  sellerSettings: {
    id: 'seller-settings',
    name: 'Settings',
    path: '/seller/settings',
    title: 'Settings',
    description: 'Seller account settings.',
    section: 'seller',
    visibility: 'seller',
    layout: 'workspace',
    parent: 'seller-dashboard',
    navPosition: ['sidebar'],
    sitemap: false,
  },
} satisfies Record<string, RouteDefinition>;
